(function () {
  "use strict";

  window.COLOR_FLASK_DATA = {
    version: "2.1.0",
    app: {
      name: "Prism Pour",
      shortName: "Prism Pour",
      koreanTitle: "프리즘 포어",
      subtitle: "빛나는 액체를 분리해 완성하는 프리미엄 퍼즐",
      openingCopy: "반가워요! 오늘도 감각적인 퍼즐 한 판 어떠세요?",
      installCopy: "홈 화면에 추가하면 더 빠르게 Prism Pour를 열 수 있어요."
    },
    defaultCapacity: 4,
    flaskOptions: [5, 10, 15, 20],
    difficulties: [
      {
        key: "beginner",
        label: "초급",
        accent: "mint",
        description: "빈 플라스크가 넉넉해서 기본 감각을 익히기 좋은 단계"
      },
      {
        key: "medium",
        label: "중급",
        accent: "sky",
        description: "색상 수가 늘어나며 중간 정리 공간 운영이 중요한 단계"
      },
      {
        key: "advanced",
        label: "고급",
        accent: "violet",
        description: "빈 칸을 아끼며 선행 계획이 필요한 본격적인 단계"
      },
      {
        key: "hard",
        label: "하드모드",
        accent: "rose",
        description: "깊은 순서 설계와 집중력이 필요한 최고 난도 테스트"
      }
    ],
    palette: {
      plum: { label: "딥 퍼플", hex: "#6F3DFF" },
      mint: { label: "민트", hex: "#19E3B2" },
      sky: { label: "스카이", hex: "#47D7FF" },
      rose: { label: "로즈", hex: "#FF5A99" },
      amber: { label: "앰버", hex: "#FF9F1C" },
      teal: { label: "틸", hex: "#00C2B8" },
      coral: { label: "코랄", hex: "#FF6B57" },
      indigo: { label: "인디고", hex: "#4C6FFF" },
      lime: { label: "라임", hex: "#B7DE2F" },
      violet: { label: "바이올렛", hex: "#C774FF" },
      sun: { label: "선샤인", hex: "#FFD93D" },
      ocean: { label: "오션", hex: "#008CFF" },
      peach: { label: "피치", hex: "#FFB277" },
      jade: { label: "제이드", hex: "#17B36B" },
      berry: { label: "베리", hex: "#D93E82" },
      slate: { label: "슬레이트", hex: "#9BA7B7" }
    },
    stages: [
      {
        id: "beginner-1",
        globalOrder: 1,
        order: 1,
        difficulty: "beginner",
        title: "첫 물방울",
        description: "같은 색 블록을 모으는 기본 패턴을 가볍게 익히는 시작 스테이지",
        flaskCount: 5,
        colors: 3,
        capacity: 4,
        hintLimit: 3,
        par: 10,
        tubes: [
          ["mint", "sky", "mint", "mint"],
          ["plum", "mint", "sky", "plum"],
          [],
          ["plum", "sky", "sky", "plum"],
          []
        ]
      },
      {
        id: "beginner-2",
        globalOrder: 2,
        order: 2,
        difficulty: "beginner",
        title: "부드러운 교차",
        description: "보이는 수는 쉬워 보여도 순서를 잘못 잡으면 다시 비워야 하는 구조",
        flaskCount: 5,
        colors: 3,
        capacity: 4,
        hintLimit: 3,
        par: 8,
        tubes: [
          ["plum", "mint", "sky", "sky"],
          ["mint", "plum", "plum", "mint"],
          ["sky", "sky", "mint", "plum"],
          [],
          []
        ]
      },
      {
        id: "beginner-3",
        globalOrder: 3,
        order: 3,
        difficulty: "beginner",
        title: "넓은 작업대",
        description: "플라스크 수는 늘어나지만 빈 칸이 많아 전체 흐름을 읽기 쉬운 확장형 퍼즐",
        flaskCount: 10,
        colors: 6,
        capacity: 4,
        hintLimit: 3,
        par: 19,
        tubes: [
          ["rose", "mint", "plum", "amber"],
          ["teal", "amber", "amber", "teal"],
          ["amber", "mint", "plum", "teal"],
          ["mint", "sky", "rose", "rose"],
          [],
          [],
          ["mint", "sky", "teal", "rose"],
          [],
          [],
          ["sky", "plum", "sky", "plum"]
        ]
      },
      {
        id: "medium-1",
        globalOrder: 4,
        order: 1,
        difficulty: "medium",
        title: "갈라지는 길",
        description: "빈 플라스크가 줄어들며 중간 정리용 공간을 어떻게 남길지 판단해야 하는 단계",
        flaskCount: 10,
        colors: 7,
        capacity: 4,
        hintLimit: 3,
        par: 23,
        tubes: [
          ["mint", "amber", "sky", "amber"],
          ["teal", "coral", "mint", "teal"],
          ["rose", "mint", "mint", "rose"],
          ["sky", "coral", "amber", "rose"],
          ["teal", "coral", "coral", "plum"],
          ["plum", "plum", "sky", "plum"],
          [],
          [],
          [],
          ["sky", "amber", "teal", "rose"]
        ]
      },
      {
        id: "medium-2",
        globalOrder: 5,
        order: 2,
        difficulty: "medium",
        title: "교차 반응",
        description: "눈앞의 합치기보다 나중에 열리는 빈 공간을 먼저 계산해야 하는 단계",
        flaskCount: 10,
        colors: 7,
        capacity: 4,
        hintLimit: 3,
        par: 21,
        tubes: [
          ["amber", "mint", "rose", "plum"],
          ["plum", "teal", "rose", "mint"],
          ["coral", "rose", "sky", "amber"],
          ["sky", "coral", "sky", "mint"],
          ["teal", "teal", "teal", "rose"],
          [],
          ["coral", "mint", "plum", "plum"],
          [],
          ["sky", "amber", "coral", "amber"],
          []
        ]
      },
      {
        id: "medium-3",
        globalOrder: 6,
        order: 3,
        difficulty: "medium",
        title: "복층 정리대",
        description: "15개 플라스크에서 넓은 시야와 중간 저장소 운영이 핵심인 넓은 판형 퍼즐",
        flaskCount: 15,
        colors: 10,
        capacity: 4,
        hintLimit: 3,
        par: 33,
        tubes: [
          ["violet", "plum", "coral", "mint"],
          ["violet", "lime", "teal", "sky"],
          [],
          ["teal", "rose", "rose", "rose"],
          [],
          ["lime", "lime", "indigo", "coral"],
          ["plum", "rose", "coral", "sky"],
          [],
          ["indigo", "mint", "amber", "indigo"],
          ["sky", "violet", "coral", "lime"],
          ["teal", "violet", "amber", "indigo"],
          ["sky", "plum", "mint", "amber"],
          [],
          [],
          ["mint", "teal", "amber", "plum"]
        ]
      },
      {
        id: "advanced-1",
        globalOrder: 7,
        order: 1,
        difficulty: "advanced",
        title: "정교한 분기",
        description: "비슷한 색 무리가 많아 상단 블록 구조를 미리 읽는 시야가 중요한 단계",
        flaskCount: 15,
        colors: 11,
        capacity: 4,
        hintLimit: 3,
        par: 41,
        tubes: [
          ["sky", "lime", "coral", "teal"],
          ["sun", "rose", "amber", "sun"],
          ["plum", "mint", "violet", "indigo"],
          [],
          ["mint", "coral", "amber", "indigo"],
          ["lime", "plum", "sun", "rose"],
          ["teal", "indigo", "lime", "amber"],
          [],
          ["mint", "plum", "coral", "lime"],
          ["indigo", "amber", "sky", "teal"],
          [],
          [],
          ["mint", "violet", "sky", "violet"],
          ["coral", "sky", "plum", "teal"],
          ["rose", "violet", "rose", "sun"]
        ]
      },
      {
        id: "advanced-2",
        globalOrder: 8,
        order: 2,
        difficulty: "advanced",
        title: "밀도 높은 층",
        description: "빈 플라스크가 적어서 잠깐 비운 공간을 바로 회수하는 운영 감각이 필요한 단계",
        flaskCount: 15,
        colors: 11,
        capacity: 4,
        hintLimit: 3,
        par: 38,
        tubes: [
          ["amber", "plum", "coral", "sun"],
          ["teal", "rose", "amber", "teal"],
          [],
          [],
          [],
          ["amber", "violet", "coral", "sun"],
          ["lime", "violet", "teal", "rose"],
          ["indigo", "mint", "violet", "plum"],
          ["indigo", "violet", "rose", "coral"],
          ["plum", "sky", "mint", "coral"],
          [],
          ["sun", "amber", "teal", "sun"],
          ["indigo", "sky", "sky", "lime"],
          ["lime", "lime", "indigo", "mint"],
          ["rose", "sky", "plum", "mint"]
        ]
      },
      {
        id: "hard-1",
        globalOrder: 9,
        order: 1,
        difficulty: "hard",
        title: "깊은 파동",
        description: "20개 플라스크와 15색 구성을 다루며 깊은 선계획을 요구하는 하드 입문 퍼즐",
        flaskCount: 20,
        colors: 15,
        capacity: 4,
        hintLimit: 3,
        par: 49,
        tubes: [
          ["indigo", "sky", "berry", "berry"],
          [],
          ["jade", "lime", "coral", "sky"],
          ["lime", "violet", "teal", "ocean"],
          ["indigo", "peach", "violet", "berry"],
          ["coral", "teal", "amber", "plum"],
          ["sun", "rose", "rose", "mint"],
          [],
          ["amber", "amber", "peach", "jade"],
          ["sky", "ocean", "jade", "berry"],
          ["violet", "mint", "teal", "plum"],
          ["lime", "teal", "coral", "amber"],
          [],
          ["mint", "lime", "plum", "coral"],
          [],
          ["ocean", "violet", "peach", "mint"],
          ["jade", "sun", "sun", "ocean"],
          [],
          ["rose", "sky", "indigo", "plum"],
          ["sun", "peach", "indigo", "rose"]
        ]
      },
      {
        id: "hard-2",
        globalOrder: 10,
        order: 2,
        difficulty: "hard",
        title: "최종 증류",
        description: "색상 수가 가장 많고 빈 공간이 적어 실제 해결 경로를 길게 설계해야 하는 최종 퍼즐",
        flaskCount: 20,
        colors: 16,
        capacity: 4,
        hintLimit: 3,
        par: 57,
        tubes: [
          ["plum", "coral", "slate", "berry"],
          [],
          ["indigo", "teal", "mint", "sky"],
          [],
          ["sky", "peach", "amber", "sky"],
          ["rose", "lime", "amber", "mint"],
          [],
          [],
          ["teal", "rose", "ocean", "violet"],
          ["teal", "violet", "ocean", "coral"],
          ["plum", "berry", "rose", "peach"],
          ["amber", "slate", "jade", "berry"],
          ["sun", "slate", "jade", "ocean"],
          ["peach", "teal", "ocean", "lime"],
          ["indigo", "berry", "plum", "lime"],
          ["rose", "plum", "sun", "violet"],
          ["mint", "lime", "coral", "slate"],
          ["indigo", "violet", "jade", "indigo"],
          ["sun", "sky", "amber", "coral"],
          ["peach", "mint", "jade", "sun"]
        ]
      }
    ]
  };
}());
